/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gestalt_candidates_NativeMovieTextureProducer */

#ifndef _Included_gestalt_candidates_NativeMovieTextureProducer
#define _Included_gestalt_candidates_NativeMovieTextureProducer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gestalt_candidates_NativeMovieTextureProducer
 * Method:    init
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gestalt_candidates_NativeMovieTextureProducer_init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gestalt_candidates_NativeMovieTextureProducer
 * Method:    tryToReadNewFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gestalt_candidates_NativeMovieTextureProducer_tryToReadNewFrame
  (JNIEnv *, jobject);

/*
 * Class:     gestalt_candidates_NativeMovieTextureProducer
 * Method:    requestOpenGlTextureId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gestalt_candidates_NativeMovieTextureProducer_requestOpenGlTextureId
  (JNIEnv *, jobject);

/*
 * Class:     gestalt_candidates_NativeMovieTextureProducer
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gestalt_candidates_NativeMovieTextureProducer_update
  (JNIEnv *, jobject);

/*
 * Class:     gestalt_candidates_NativeMovieTextureProducer
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gestalt_candidates_NativeMovieTextureProducer_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     gestalt_candidates_NativeMovieTextureProducer
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gestalt_candidates_NativeMovieTextureProducer_getHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
