/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gestalt_candidates_NativeDrawable */

#ifndef _Included_gestalt_candidates_NativeDrawable
#define _Included_gestalt_candidates_NativeDrawable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gestalt_candidates_NativeDrawable
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gestalt_candidates_NativeDrawable_init
  (JNIEnv *, jobject);

/*
 * Class:     gestalt_candidates_NativeDrawable
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gestalt_candidates_NativeDrawable_draw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
